### ISSUE TITLE
"SEVERE"  log level should be highlighted in red instead of green

### ISSUE THREAD

**Issue by unkarjedy** [JetBrains/IntelliJ-Log-Analyzer#24]
![image](https://user-images.githubusercontent.com/3989292/188685697-491f1929-d67c-431a-b3f7-63bd484bea74.png)

**Comment by unkarjedy** [comment]
Also "WARN" could be orange in this case, not "RED"

**Comment by annikovk** [comment]
What SEVERE should be in your opinion?

**Comment by annikovk** [comment]
Why SEVERE should be red? If I remember correctly - there are cases when it does not indicate an error, aren't they?

**Comment by unkarjedy** [comment]
From `java.util.logging.Level#SEVERE`
>SEVERE is a message level indicating a serious failure.
>
>In general SEVERE messages should describe events that are
of considerable importance and which will prevent normal
program execution.   They should be reasonably intelligible
to end users and to system administrators.

**Comment by unkarjedy** [comment]
And there is no "ERROR" in `java.util.logging.Level#standardLevels`, only "SEVERE":
```java
    private static final Level[] standardLevels = {
        OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL
    };
```

**Comment by annikovk** [comment]
Thank you for the explanation. Fixed
